script «update-bacula» v1.14
* 'set -u' to abort execution on empty variables
* use POSIX shell construction :- for setting default values
* "maildir" job detection with shell builtin variable expansion
* on_exit(): proper cleanup if execution is interrupted
* replace "host" with "getent hosts" for FQDN resolution

diff --git a/usr/update-bacula b/usr/update-bacula
--- a/usr/update-bacula
+++ b/usr/update-bacula
@@ -1,40 +1,39 @@
 #!/bin/sh
 # Update Bacula configuration for Director and Storage Daemon services.
 # Author:   Teodor 'døru' MICU <mteodor@gmail.com>
-# Revision: Thu Jan 24 15:16:08 UTC 2013
+# Revision: Thu Jan 24 15:48:05 UTC 2013
 #
 # License: Public Domain
 # Location: /usr/local/sbin/
 #
-# Version: 1.13
+# Version: 1.14
 
 
 PATH="/usr/sbin:/usr/bin:/sbin:/bin"
-set -e
+set -eu
 
-DESC="Bacula configurator"
+DESC="Updating Bacula configuration ..."
 NAME=update-bacula
 
-# Read configuration variable file if it is present
+# read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-# configuration file used by this script
-[ -n "$CONF" ] || CONF="/etc/bacula/backups.list"
-[ -n "$STORAGEDISK" ] || STORAGEDISK="/srv/bacula"
-[ -n "$STORAGEPW" ] || STORAGEPW="shiezoodeipu6Aegakie"
+# set internal variables to their default values (if unset)
+CONF=${CONF:-/etc/bacula/backups.list}
+STORAGEDISK=${STORAGEDISK:-/srv/bacula}
+STORAGEPW=${STORAGEPW:-kaidae8Johtei7ieShie}
 
-# where are kept the filesets for each CLIENT+JOB combination
+# where to find the filesets for all jobs
 BDFS="/etc/bacula/director/filesets"
 
-# where are kept the files generated by this script
-[ -n "$BCACHE" ] || BCACHE="/var/cache/bacula"
-# required tests for CACHE directories
+# where to keep the config files generated by this script
+BCACHE=${BCACHE:-/var/cache/bacula}
 if echo "$BCACHE" | grep -q -E '\s'; then
 	echo "E: cache directory '$BCACHE' must not contain spaces!" >&2
 	exit 1
 fi
-[ "$BCACHE" != "/" ] || exit 2			# top level directory is forbidden
-[ -e "$BCACHE" -a ! -d "$BCACHE" ] && exit 3	# target must be a directory
+[ "$BCACHE" != "/" ] || exit 2				# top level directory is forbidden
+[ -e "$BCACHE" -a ! -d "$BCACHE" ] && exit 3		# target must be a directory
 
 if [ ! -f "$CONF" ]; then
 	echo "E: configuration file '$CONF' does not exist!" >&2
@@ -42,7 +41,8 @@ if [ ! -f "$CONF" ]; then
 fi
 
 # mkbanner FILE
-mkbanner(){
+mkbanner()
+{
 	[ -z "$1" -o -s "$1" ] && return 0
 	cat > $1 <<__EOF__
 #
@@ -57,7 +57,8 @@ __EOF__
 }
 
 # mkclient CLIENT
-mkclient(){
+mkclient()
+{
 	[ -s ${BCACHE}/director/client_${CLIENT}.conf ] && return 0
 
 	mkbanner ${BCACHE}/director/client_${CLIENT}.conf
@@ -78,12 +79,14 @@ __EOF__
 }
 
 # mkfilesets CLIENT
-mkfilesets(){
+mkfilesets()
+{
 	mkbanner ${BCACHE}/director/filesets_${CLIENT}.conf
 	for JOB in $JOBS; do
-		if printf "$JOB" | grep -q maildir; then
+		USER=${JOB#maildir-}
+		if [ "$JOB" != "$USER" ]; then
+			# automatically generate fileset
 			INCLUDEFILE=${BCACHE}/director/${CLIENT}--${JOB}_files.list
-			USER=$(printf "$JOB" | sed -e "s%maildir.%%")
 			U=$(printf "$USER" | cut -b1)
 			printf "/home/${U}/${USER}/mail" > $INCLUDEFILE
 			cat <<__EOF__
@@ -124,7 +127,8 @@ __EOF__
 }
 
 # mkpools CLIENT
-mkpools(){
+mkpools()
+{
 	mkbanner ${BCACHE}/director/pools_${CLIENT}.conf
 	for JOB in $JOBS; do cat <<__EOF__
 Pool {
@@ -142,7 +146,8 @@ __EOF__
 }
 
 # mkstorage CLIENT
-mkstorage(){
+mkstorage()
+{
 	[ -s ${BCACHE}/director/storage_${CLIENT}.conf ] && return 0
 
 	mkbanner ${BCACHE}/director/storage_${CLIENT}.conf
@@ -172,12 +177,14 @@ Device {
 }
 
 __EOF__
-	[ -e "${STORAGEDISK}/${CLIENT}" ] || install -v -o bacula -g tape -m 0775 -d "${STORAGEDISK}/${CLIENT}"
+	[ -e "${STORAGEDISK}/${CLIENT}" ] || \
+	  install -v -o bacula -g tape -m 0775 -d "${STORAGEDISK}/${CLIENT}"
 	return 0
 }
 
 # mkjobs CLIENT
-mkjobs(){
+mkjobs()
+{
 	mkbanner ${BCACHE}/director/jobs_${CLIENT}_backup.conf
 	for JOB in $JOBS; do cat <<__EOF__
 Job {
@@ -222,6 +229,13 @@ __EOF__
 
 
 ####################========== main() ==========####################
+TMPFILE=$(mktemp)
+on_exit()
+{
+	rm -f $TMPFILE
+}
+trap on_exit EXIT INT QUIT TERM
+
 [ -e "${BCACHE}/director" ] || mkdir -p ${BCACHE}/director
 [ -e "${BCACHE}/storage" ] || mkdir -p ${BCACHE}/storage
 [ -e "$BDFS" ] || mkdir -p $BDFS
@@ -230,9 +244,10 @@ rm -f ${BCACHE}/director/*maildir*_files.list
 rm -f ${BCACHE}/storage/file_*.conf
 rm -f ${BCACHE}/director.conf ${BCACHE}/storage.conf
 
-echo "Running $DESC:"
-TMPFILE=$(mktemp)
-grep '^[A-Za-z0-9]' $CONF | sed -e "s%\s*|\s*%|%g" > $TMPFILE
+# remove white spaces before or after '|' delimiter
+grep '^[A-Za-z0-9]' $CONF | sed "s%\s*|\s*%|%g" > $TMPFILE
+
+echo "$DESC"
 while read LINE; do
 	CLIENT=$(printf "$LINE" | cut -d\| -f1)
 	[ "$CLIENT" ] || continue
@@ -240,11 +255,12 @@ while read LINE; do
 		echo "W: non alpha-numeric character in '$CLIENT' client name (ignored)"
 		continue
 	fi
-	if host $CLIENT | grep -q NXDOMAIN; then
-		echo "W: host '$CLIENT' not found (ignored)"
+
+	CLIENTADDR=$(getent hosts "$CLIENT" | cut '-d ' -f5)
+	if [ -z "$CLIENTADDR" ]; then
+		echo "W: host '$CLIENT' not found (record ignored)"
 		continue
 	fi
-	CLIENTADDR=$(host $CLIENT | cut '-d ' -f1)
 
 	PASSWORD=$(printf "$LINE" | cut -d\| -f2)
 	[ "$PASSWORD" ] || continue
@@ -262,13 +278,13 @@ while read LINE; do
 		echo "W: non alpha-numeric character in '$STORAGE' storage host ($CLIENT ignored)"
 		continue
 	fi
-	if host $STORAGE | grep -q NXDOMAIN; then
+	STORAGEADDR=$(getent hosts "$STORAGE" | cut '-d ' -f5)
+	if [ -z "$STORAGEADDR" ]; then
 		echo "W: storage host '$STORAGE' not found ($CLIENT ignored)"
 		continue
 	fi
-	STORAGEADDR=$(host $STORAGE | cut '-d ' -f1)
 
-	RETENTION=$(printf "$LINE" | cut -d\| -f5 | sed -e "s%\s*,\s*%,%g")
+	RETENTION=$(printf "$LINE" | cut -d\| -f5 | sed "s%\s*,\s*%,%g")
 	[ "$RETENTION" ] || continue
 	FRETENTION=$(printf "$RETENTION" | cut -d, -f1)
 	[ "$FRETENTION" ] || continue
@@ -297,7 +313,7 @@ while read LINE; do
 	mkpools
 	mkstorage
 	mkjobs
-	echo "+ $CLIENT: $JOBS ($SCHEDULE schedule)"
+	echo "+ jobs for host $CLIENT: $JOBS („$SCHEDULE” schedule)"
 done < $TMPFILE
 
 mkbanner ${BCACHE}/director.conf
@@ -311,6 +327,4 @@ cd ${BCACHE}/storage
 for FILE in *.conf; do
 	echo "@${BCACHE}/storage/$FILE" >> ${BCACHE}/storage.conf
 done
-
-rm -f $TMPFILE
 :
