Group | MAC address | Host | ..
Moved MAC address on the second field due to its constant size.

diff --git a/usr/update-dhcp-groups b/usr/update-dhcp-groups
--- a/usr/update-dhcp-groups
+++ b/usr/update-dhcp-groups
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Update configuration files for all DHCP groups.
 # Author:   Teodor MICU <mteodor@gmail.com>
-# Revision: July 04, 2012
+# Revision: October 05, 2012
 #
 # Location: /usr/local/sbin/
 
@@ -26,7 +26,7 @@ on_exit()
 }
 trap on_exit EXIT INT QUIT TERM
 
-#Group | Host | MAC address | ..
+#Group | MAC address | Host | ..
 LANG=C
 while read LINE; do
 	echo "$LINE" | grep -q "^\s*#" && continue
@@ -41,15 +41,7 @@ while read LINE; do
 		continue
 	fi
 
-	HOST=$(echo "$LINE" | cut '-d|' -f2)
-	if IPADDR=$(getent hosts $HOST); then
-		IPADDR=$(echo "$IPADDR" | awk '{ print $1 }')
-	else
-		echo "E: host '${HOST}' not found.. record ignored" >&2
-		continue
-	fi
-
-	MACADDR=$(echo "$LINE" | cut '-d|' -f3)
+	MACADDR=$(echo "$LINE" | cut '-d|' -f2)
 	if [ -z "$MACADDR" ]; then
 		echo "E: empty MAC address for host '$HOST'.. record ignored" >&2
 		continue
@@ -58,6 +50,14 @@ while read LINE; do
 		continue
 	elif [ $(echo "$MACADDR" | awk -F: '{ print NF }') -ne 6 ]; then
 		echo "E: invalid MAC address for host '$HOST'.. record ignored" >&2
+		continue
+	fi
+
+	HOST=$(echo "$LINE" | cut '-d|' -f3)
+	if IPADDR=$(getent hosts $HOST); then
+		IPADDR=$(echo "$IPADDR" | awk '{ print $1 }')
+	else
+		echo "E: host '${HOST}' not found.. record ignored" >&2
 		continue
 	fi
 
